version: '3.8'

services:
  
  # Backend Service
  backend:
    image: ${BACKEND_IMAGE:-ghcr.io/dilan/nasa-backend:1.0}
    environment:
      - PORT=${BACKEND_PORT:-4200}
      - VERSION=${VERSION:-1.0.0}
      - DEMO_KEY=${DEMO_KEY}

    networks:
      - nasa_network
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 5s
        order: start-first
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT:-4200}/api/v1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Website
  site:
    image: ${SITE_IMAGE:-ghcr.io/dilan/nasa-frontend:1.0}
    networks:
      - nasa_network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 5s
        order: start-first
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Ingress Proxy (Nginx)
  nginx:
    image: nginx:alpine
    ports:
    - target: 80
      published: 80
      mode: host
    - target: 443
      published: 443
      mode: host
    networks:
      - nasa_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/start-nginx.sh:/start-nginx.sh
      - /opt/certbot/www:/var/www/certbot
      - /opt/certbot/conf:/etc/letsencrypt # certbot (SSL)

    command: ["/bin/sh", "-c", "apk add --no-cache curl && chmod +x /start-nginx.sh && /start-nginx.sh"]
    deploy:
      mode: global  # run on all nodes to handle ingress
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

# Networks
networks:
  nasa_network:
    driver: overlay
    attachable: false

 